markdown: maruku
pygments: true
safe: true

foo: bar

kramdown:
    auto_ids: false
    #template: string://abc
    enable_codearay: true
    link_defs: "--- !ruby/object:File\nfoo: bar"
    
maruku:
  foo: bar
  use_tex:    true
  use_divs:   true
  png_engine: blahtex
  png_dir:    images/latex/
  png_url:    /images/latex/
    
#kramdown:
    #template: "foo"