markdown: kramdown
pygments: true
safe: true

foo: bar

kramdown:
    auto_ids: false
    #template: string://abc
    enable_codearay: true
    link_defs: "{foo: ['url', 'title']}"
    
#kramdown:
    #template: "foo"